services:
#    acme_basiccms.basic_cms.phpcr.initializer:
#        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
#        arguments:
#            - My custom initializer
#            - ["/cms/pages", "/cms/posts", "/cms/routes"]
#        tags:
#            - { name: doctrine_phpcr.initializer }
    acme_basiccms.phpcr.initializer.site:
            class: Acme\BasicCmsBundle\Initializer\SiteInitializer
            tags:
                - { name: doctrine_phpcr.initializer, priority: 50 }

    acme.basic_cms.admin.page:
        class: Acme\BasicCmsBundle\Admin\PageAdmin
        arguments:
            - ''
            - Acme\BasicCmsBundle\Document\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS',label: Page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    acme.basic_cms.admin.post:
        class: Acme\BasicCmsBundle\Admin\PostAdmin
        arguments:
          - ''
          - Acme\BasicCmsBundle\Document\Post
          - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS',label: 'Blog Posts' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    acme.basic_cms.menu_provider:
            class: Symfony\Cmf\Bundle\MenuBundle\Provider\PhpcrMenuProvider
            arguments:
                - '@cmf_menu.factory'
                - '@doctrine_phpcr'
                - /cms/pages
            calls:
                - [setRequest, ["@?request="]]
            tags:
                - { name: knp_menu.provider }